# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c2b77e4b62f3de295bf96e88550ed9d74492903d71c936c8ec16f14c72a59ed686989a05a1f1ad19891ec94e993ee19cb1f863c1d2fe34fa19175e8c98eff7d

test:
  secret_key_base: 02810ae0e0057131191f670ede36c121ab580ff15c187edbe4d0ab887e182b281ed4d7d6b69ac9a312368e843a675355a922e7c3ae383e9abddc702e04ad8ec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
